pool:
  name: Azure Pipelines
  demands: msbuild
  vmImage: 'windows-2019'


variables:
- name: BuildConfiguration
  value: Release

jobs:
- job: Broken
  displayName: Broken
  steps:

  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk 2.2.x'
    inputs:
      version: 2.2.x

  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk 3.1.x'
    inputs:
      version: 3.1.x

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '**/*.csproj'

  - task: MSBuild@1
    displayName: 'Build solution **/*.sln'
    inputs:
      configuration: '$(BuildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: false
      projects: '**/*.csproj'
      arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
      zipAfterPublish: True

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
    condition: succeededOrFailed()

- job: Also_Broken
  displayName: Also Broken (missing 2.2.x and 3.1.302)
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk 3.1.302'
    inputs:
      version: 3.1.302

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '**/*.csproj'

  - task: MSBuild@1
    displayName: 'Build solution **/*.sln'
    inputs:
      configuration: '$(BuildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: false
      projects: '**/*.csproj'
      arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
      zipAfterPublish: True

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
    condition: succeededOrFailed()

- job: Also_Also_Broken
  displayName: Also Also Broken (missing 2.2.x and 3.1.x)
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk 3.1.x'
    inputs:
      version: 3.1.x

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '**/*.csproj'

  - task: MSBuild@1
    displayName: 'Build solution **/*.sln'
    inputs:
      configuration: '$(BuildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: false
      projects: '**/*.csproj'
      arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
      zipAfterPublish: True

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
    condition: succeededOrFailed()

- job: Not_Broken
  displayName: Not Broken
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk 2.2.x'
    inputs:
      version: 2.2.x

  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk 3.1.302'
    inputs:
      version: 3.1.302

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '**/*.csproj'

  - task: MSBuild@1
    displayName: 'Build solution **/*.sln'
    inputs:
      configuration: '$(BuildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: false
      projects: '**/*.csproj'
      arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
      zipAfterPublish: True

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
    condition: succeededOrFailed()

